import './info-page.css';

type InfoPageProps = { kind: string; te: boolean };

const copy: Record<string, { enTitle: string; teTitle: string; enIntro: string; teIntro: string; enBody: string[]; teBody: string[] }> = {
  privacy: { enTitle: 'Privacy policy', teTitle: 'గోప్యతా విధానం', enIntro: 'Your privacy is important to Maanvi.', teIntro: 'మీ గోప్యత మాన్వికి ఎంతో ముఖ్యం.', enBody: ['We only use the information you choose to share with us to answer questions, arrange a video viewing or help with a purchase. We do not sell your information to anyone.', 'We keep conversations and booking details limited to the people helping you, and you can ask us to remove your details at any time.'], teBody: ['మీరు స్వచ్ఛందంగా ఇచ్చే సమాచారాన్ని మీ ప్రశ్నలకు సమాధానం ఇవ్వడానికి, వీడియో వీక్షణ ఏర్పాటు చేయడానికి లేదా కొనుగోలులో సహాయం చేయడానికి మాత్రమే ఉపయోగిస్తాం.', 'మీ సమాచారాన్ని ఎవరితోనూ అమ్మము. మీ వివరాలను తొలగించమని ఎప్పుడైనా మమ్మల్ని అడగవచ్చు.'] },
  terms: { enTitle: 'Terms of sale', teTitle: 'విక్రయ నిబంధనలు', enIntro: 'A clear, personal way to shop with Maanvi.', teIntro: 'మాన్వితో స్పష్టంగా, వ్యక్తిగతంగా షాపింగ్ చేయండి.', enBody: ['Our collection changes with each arrival. We confirm availability, colour, price and delivery details with you before an order is accepted.', 'Photos and AI interpretations are for reference; the real saree shown during a video viewing is the item you are choosing. We will explain any care, alteration, exchange or delivery conditions before confirming your purchase.'], teBody: ['ప్రతి కొత్త కలెక్షన్‌తో అందుబాటులో ఉన్న చీరలు మారవచ్చు. ఆర్డర్ తీసుకునే ముందు అందుబాటు, రంగు, ధర, డెలివరీ వివరాలను మీతో నిర్ధారిస్తాం.', 'ఫోటోలు, AI చిత్రాలు సూచన కోసం మాత్రమే. మీరు ఎంచుకునే అసలు చీరను వీడియో వీక్షణలో చూపిస్తాం.'] },
  cookies: { enTitle: 'Cookie policy', teTitle: 'కుకీ విధానం', enIntro: 'A simple site with minimal tracking.', teIntro: 'తక్కువ ట్రాకింగ్‌తో సరళమైన వెబ్‌సైట్.', enBody: ['Maanvi does not use advertising cookies or sell browsing data. The site may use small essential settings, such as remembering your language preference.', 'You can clear these settings through your browser at any time.'], teBody: ['మాన్వి ప్రకటన కుకీలు ఉపయోగించదు, బ్రౌజింగ్ సమాచారాన్ని అమ్మదు. మీ భాష ఎంపికను గుర్తుంచుకోవడానికి అవసరమైన చిన్న సెట్టింగ్‌లు మాత్రమే ఉండవచ్చు.', 'మీ బ్రౌజర్ ద్వారా ఈ సెట్టింగ్‌లను ఎప్పుడైనా తొలగించవచ్చు.'] },
  careers: { enTitle: 'Careers at Maanvi', teTitle: 'మాన్విలో ఉద్యోగాలు', enIntro: 'Help us bring beautiful Indian cloth closer to people everywhere.', teIntro: 'భారతీయ వస్త్రాల అందాన్ని మరింత మందికి చేరవేయడంలో మాతో కలిసి పనిచేయండి.', enBody: ['We are a small family-led saree house in Vijayawada. We welcome thoughtful people in styling, customer care, photography, logistics and craft storytelling.', 'There are no open roles listed right now. Send a short introduction through LinkedIn and we will keep it for future opportunities.'], teBody: ['మేము విజయవాడలో కుటుంబం నడిపే చిన్న చీరల ఇల్లు. స్టైలింగ్, కస్టమర్ కేర్, ఫోటోగ్రఫీ, లాజిస్టిక్స్, కళల కథనాల్లో ఆసక్తి ఉన్నవారిని స్వాగతిస్తాం.', 'ప్రస్తుతం ఖాళీలు లేవు. భవిష్యత్ అవకాశాల కోసం LinkedIn ద్వారా మీ పరిచయాన్ని పంపండి.'] },
  contact: { enTitle: 'Contact Maanvi', teTitle: 'మాన్విని సంప్రదించండి', enIntro: 'A real person is here to help.', teIntro: 'మీకు సహాయం చేయడానికి మేమున్నాం.', enBody: ['Message us on WhatsApp for availability, styling questions or a private video viewing. We speak Telugu and English.', 'Visit our home in Vijayawada or book a time online.'], teBody: ['అందుబాటు, స్టైలింగ్ ప్రశ్నలు లేదా వీడియో వీక్షణ కోసం WhatsAppలో మాకు మెసేజ్ చేయండి. మేము తెలుగు, ఇంగ్లీష్ మాట్లాడతాం.', 'విజయవాడలోని మా ఇంటికి రండి లేదా ఆన్‌లైన్‌లో సమయం బుక్ చేసుకోండి.'] },
  returns: { enTitle: 'Returns and exchanges', teTitle: 'రిటర్న్స్ మరియు మార్పులు', enIntro: 'We want you to feel sure before you choose.', teIntro: 'మీ ఎంపికపై మీకు నమ్మకం ఉండాలని మేము కోరుకుంటాం.', enBody: ['Because every saree is checked and prepared personally, return and exchange options depend on the item and its condition. We explain the applicable terms before confirming an order.', 'Please contact us as soon as possible if something arrives differently from what we confirmed with you.'], teBody: ['ప్రతి చీరను వ్యక్తిగతంగా పరిశీలించి సిద్ధం చేస్తాం. అందువల్ల రిటర్న్, మార్పు ఎంపికలు వస్తువు, దాని స్థితిపై ఆధారపడి ఉంటాయి. ఆర్డర్ ముందు వర్తించే నిబంధనలు వివరిస్తాం.', 'మీతో నిర్ధారించిన దానికంటే భిన్నంగా వస్తువు చేరితే వెంటనే మమ్మల్ని సంప్రదించండి.'] },
  shipping: { enTitle: 'Shipping and delivery', teTitle: 'షిప్పింగ్ మరియు డెలివరీ', enIntro: 'We arrange delivery with care from Vijayawada.', teIntro: 'విజయవాడ నుంచి జాగ్రత్తగా డెలివరీ ఏర్పాటు చేస్తాం.', enBody: ['Delivery timing and cost depend on the destination and the saree selected. We share both clearly before you confirm your order.', 'For international requests, message us and we will check the best available option for your location.'], teBody: ['డెస్టినేషన్, ఎంచుకున్న చీర ఆధారంగా డెలివరీ సమయం, ఖర్చు మారవచ్చు. ఆర్డర్ ముందు రెండింటినీ స్పష్టంగా చెబుతాం.', 'అంతర్జాతీయ డెలివరీ కోసం మాకు మెసేజ్ చేయండి. మీ ప్రాంతానికి అందుబాటులో ఉన్న ఉత్తమ మార్గాన్ని పరిశీలిస్తాం.'] },
  services: { enTitle: 'Services', teTitle: 'సేవలు', enIntro: 'A little more help choosing the right drape.', teIntro: 'మీకు సరైన చీరను ఎంచుకోవడంలో మరింత సహాయం.', enBody: ['Book a private video viewing, ask for a colour or occasion-based edit, or visit us in Vijayawada. We unfold the real sarees and talk through the details with you.', 'Start with our collection book, then meet the actual pieces before deciding.'], teBody: ['ప్రైవేట్ వీడియో వీక్షణ బుక్ చేయండి, రంగు లేదా వేడుక ఆధారంగా ఎంపిక అడగండి, లేదా విజయవాడలో మమ్మల్ని కలవండి.', 'కలెక్షన్ బుక్‌తో ప్రారంభించి, నిర్ణయం తీసుకునే ముందు అసలు చీరలను చూడండి.'] },
  company: { enTitle: 'About Maanvi', teTitle: 'మాన్వి గురించి', enIntro: 'A family saree house from Vijayawada, since 2017.', teIntro: '2017 నుంచి విజయవాడలో కుటుంబం నడిపే చీరల ఇల్లు.', enBody: ['Maanvi brings together sarees and fabrics from across India with a Telugu-first, personal way of helping you choose.', 'Every conversation begins with the cloth: its colour, border, weave, movement and the occasion it is meant for.'], teBody: ['భారతదేశం నలుమూలల నుంచి చీరలు, వస్త్రాలను తీసుకువచ్చి, తెలుగు-first వ్యక్తిగత సేవతో మీకు ఎంపికలో సహాయం చేస్తాం.', 'ప్రతి సంభాషణ వస్త్రంతోనే మొదలవుతుంది: దాని రంగు, అంచు, నేత, కదలిక, అది సరిపోయే వేడుక.'] },
  sitemap: { enTitle: 'Sitemap', teTitle: 'సైట్‌మ్యాప్', enIntro: 'A simple map of the Maanvi website.', teIntro: 'మాన్వి వెబ్‌సైట్‌లోని పేజీల సరళమైన మ్యాప్.', enBody: ['Explore the home journey, collection book, private viewing, family story, store visit and information pages from the footer.', 'If you cannot find something, message us on WhatsApp and a member of our family will help.'], teBody: ['హోమ్, కలెక్షన్ బుక్, ప్రైవేట్ వీక్షణ, కుటుంబ కథ, దుకాణం మరియు సమాచార పేజీలను ఫుటర్ నుంచి చూడండి.', 'ఏదైనా దొరకకపోతే WhatsAppలో మాకు మెసేజ్ చేయండి. మా కుటుంబ సభ్యులు సహాయం చేస్తారు.'] },
};

export default function InfoPage({ kind, te }: InfoPageProps) {
  const item = copy[kind] ?? copy.company;
  const title = te ? item.teTitle : item.enTitle;
  const intro = te ? item.teIntro : item.enIntro;
  const body = te ? item.teBody : item.enBody;
  const careers = kind === 'careers';
  return <article className="info-page"><p className="chapter-kicker">{te ? 'మాన్వి · సమాచారం' : 'MAANVI · INFORMATION'}</p><h1>{title}</h1><p className="info-intro">{intro}</p>{body.map(text => <p key={text}>{text}</p>)}{careers && <a className="thread-button" href="https://www.linkedin.com/company/maanvi-sarees/" target="_blank" rel="noreferrer">{te ? 'LinkedInలో మమ్మల్ని చూడండి' : 'Find Maanvi on LinkedIn'}</a>}</article>;
}
