import { useState, useRef, useEffect } from 'react';

export default function Viewing({ te, favorites }: { te: boolean; favorites: string[] }) {
  const t = (a: string, b: string) => te ? a : b;
  const [step, setStep] = useState(0);
  const [brief, setBrief] = useState({ occasion: '', fabric: '', budget: '', colors: '', notes: '', name: '', email: '', country: '' });
  const heading = useRef<HTMLHeadingElement>(null);
  const first = useRef(true);
  useEffect(() => { if (first.current) { first.current = false; return; } heading.current?.focus(); }, [step]);
  const field = (key: keyof typeof brief, value: string) => setBrief(s => ({ ...s, [key]: value }));
  const url = new URL(import.meta.env.VITE_CALENDLY_URL || 'https://calendly.com/gvrao189/30min');
  url.searchParams.set('name', brief.name); url.searchParams.set('email', brief.email);
  url.searchParams.set('a1', brief.occasion); url.searchParams.set('a2', brief.budget);
  url.searchParams.set('a3', [brief.fabric, brief.colors, brief.notes, brief.country, favorites.length ? `${favorites.length} saved archive chapters` : ''].filter(Boolean).join(' · '));
  const translated: Record<string,string> = { Wedding:'పెళ్లి', Festival:'పండుగ', Everyday:'రోజువారీ', Gift:'బహుమతి', 'For myself':'నా కోసం', Cotton:'కాటన్', 'Silk / Pattu':'పట్టు', 'Traditional weaves':'సాంప్రదాయ చేనేత', 'Dress materials / Half sarees':'డ్రెస్ మెటీరియల్స్ / లంగా ఓణీలు', 'Curate for me':'మీరే సూచించండి', Flexible:'నచ్చినదాన్ని బట్టి', 'Under ₹10,000':'₹10,000 లోపు' };
  const display = (value:string) => te ? translated[value] || value : value;
  const titles = [t('మీ వేడుక గురించి చెప్పండి.', 'Tell us about your occasion.'), t('మీకు నచ్చినవి ఏమిటి?', 'What feels like you?'), t('మిమ్మల్ని కలుద్దాం.', 'Let’s meet.'), t('మీ కోసం సిద్ధమవుతాం.', 'A viewing, prepared around you.')];
  return <section className="viewing-page">
    <aside className="viewing-aside"><p className="chapter-kicker">{t('మాన్వితో ముఖాముఖి', 'A PRIVATE VIEWING')}</p><h1>{t('ఎక్కడున్నా,\nమనసుకు దగ్గరగా.', 'Wherever you are,\na little closer.')}</h1><p>{t('మీ వేడుక, మీ అభిరుచి, మీ బడ్జెట్. మీకు సరిపోయే చీరలను వీడియో కాల్‌లో దగ్గరగా చూపిస్తాం.', 'Your occasion, your taste, your budget. We’ll unfold a thoughtful selection of sarees for you, live on a video call.')}</p><span className="viewing-time">30 <small>{t('నిమిషాలు · మీ కోసం', 'minutes · just for you')}</small></span><a href="https://wa.me/919182242429" target="_blank" rel="noreferrer">{t('తెలుగులో మాట్లాడుకుందాం ↗', 'Talk to our family on WhatsApp ↗')}</a></aside>
    <div className="viewing-form"><div className="viewing-progress" aria-label={t(`దశ ${step + 1} / 4`, `Step ${step + 1} of 4`)}>{[0,1,2,3].map(i=><span key={i} className={i<=step?'filled':''}/>)}</div><p className="chapter-kicker">0{step+1} / 04</p><h2 ref={heading} tabIndex={-1}>{titles[step]}</h2>
      <form onSubmit={e=>{e.preventDefault();setStep(s=>Math.min(3,s+1));}}>
        {step===0&&<><label>{t('సందర్భం', 'Occasion')}<select required value={brief.occasion} onChange={e=>field('occasion',e.target.value)}><option value="">{t('ఎంచుకోండి', 'Choose an occasion')}</option>{[['Wedding','పెళ్లి'],['Festival','పండుగ'],['Everyday','రోజువారీ'],['Gift','బహుమతి'],['For myself','నా కోసం']].map(([en,teText])=><option key={en} value={en}>{te?teText:en}</option>)}</select></label><label>{t('ఎలాంటి చీరలు చూడాలనుకుంటున్నారు?', 'What would you like to explore?')}<select required value={brief.fabric} onChange={e=>field('fabric',e.target.value)}><option value="">{t('ఎంచుకోండి', 'Choose a fabric')}</option>{[['Cotton','కాటన్'],['Silk / Pattu','పట్టు'],['Traditional weaves','సాంప్రదాయ చేనేత'],['Dress materials / Half sarees','డ్రెస్ మెటీరియల్స్ / లంగా ఓణీలు'],['Curate for me','మీరే సూచించండి']].map(([en,teText])=><option key={en} value={en}>{te?teText:en}</option>)}</select></label></>}
        {step===1&&<><label>{t('బడ్జెట్', 'Comfortable budget')}<select required value={brief.budget} onChange={e=>field('budget',e.target.value)}><option value="">{t('ఎంచుకోండి', 'Choose a range')}</option>{['Under ₹10,000','₹10,000–₹20,000','₹20,000–₹35,000','₹35,000–₹60,000','₹60,000+'].map(v=><option key={v} value={v}>{display(v)}</option>)}<option value="Flexible">{t('నచ్చినదాన్ని బట్టి', 'Flexible')}</option></select></label><label>{t('ఇష్టమైన రంగులు', 'Colours you love')}<input value={brief.colors} onChange={e=>field('colors',e.target.value)} placeholder={t('ఉదా: ఆకుపచ్చ, ఎరుపు, క్రీమ్', 'For example: green, red, ivory')}/></label><label>{t('మాకు చెప్పాలనుకున్నవి', 'Anything else we should know')}<textarea rows={3} value={brief.notes} onChange={e=>field('notes',e.target.value)} /></label></>}
        {step===2&&<><label>{t('మీ పేరు', 'Your name')}<input autoComplete="name" required value={brief.name} onChange={e=>field('name',e.target.value)}/></label><label>{t('ఈమెయిల్', 'Email')}<input autoComplete="email" type="email" required value={brief.email} onChange={e=>field('email',e.target.value)}/></label><label>{t('దేశం / టైమ్ జోన్', 'Country / time zone')}<input value={brief.country} onChange={e=>field('country',e.target.value)} placeholder="India / California / London…"/></label><p className="form-note">{t('మీ వివరాలు అపాయింట్‌మెంట్ కోసం మాత్రమే. తదుపరి దశలో Calendly ద్వారా సమయం ఎంచుకోండి.', 'Your details are for your appointment. In the next step, choose a time through Calendly.')}</p></>}
        {step===3&&<><dl className="viewing-summary"><dt>{t('పేరు', 'Name')}</dt><dd>{brief.name}</dd><dt>{t('సందర్భం / చీరలు', 'Occasion / fabric')}</dt><dd>{display(brief.occasion)} · {display(brief.fabric)}</dd><dt>{t('బడ్జెట్', 'Budget')}</dt><dd>{display(brief.budget)}</dd><dt>{t('రంగులు', 'Colours')}</dt><dd>{brief.colors||t('మీరే సూచించండి', 'Curate for me')}</dd></dl><p>{t('సమయం ఎంచుకున్న తర్వాతే మీ బుకింగ్ పూర్తవుతుంది. కాల్‌లో అసలు చీర, అంచు, రంగు, మడత అన్నీ చూపిస్తాం.', 'Complete your booking by choosing a time. On the call, see the actual saree, its border, colour and drape.')}</p><a className="thread-button" href={url.toString()} target="_blank" rel="noreferrer">{t('సమయం ఎంచుకోండి', 'Choose an appointment time')} ↗</a><p className="form-note">{t('కొనుగోలు ముందు పూర్తి ధర, డెలివరీ వివరాలు వ్యక్తిగతంగా నిర్ధారిస్తాం.', 'We confirm the full price and delivery details personally before payment.')}</p></>}
        <div className="viewing-actions">{step>0&&<button type="button" onClick={()=>setStep(s=>s-1)}>← {t('వెనుకకు', 'Back')}</button>}{step<3&&<button className="thread-button" type="submit">{t('కొనసాగించండి', 'Continue')} →</button>}</div>
      </form>
    </div>
  </section>;
}
