import { useEffect, useMemo, useState } from "react";
import "./App.css";

type Route = "home" | "archive" | "private-shopping" | "bridal" | "guide" | "story" | "visit" | "book";
type Quiz = { occasion: string; forWhom: string; explore: string[]; budget: string; colors: string[]; colorNotes: string; notes: string; name: string; email: string; phone: string; country: string };
const routes: Record<Route, string> = { home: "/", archive: "/archive", "private-shopping": "/private-shopping", bridal: "/bridal", guide: "/saree-guide", story: "/our-story", visit: "/visit", book: "/book" };
const navItems: [Route, string][] = [["archive", "The Archive"], ["private-shopping", "Private Shopping"], ["bridal", "Bridal"], ["guide", "Across India"], ["story", "Our Story"], ["visit", "Visit"]];
const externalLinks = {
  calendly: "https://calendly.com/gvrao189/30min",
  whatsapp: "https://wa.me/919182242429",
  instagram: "https://www.instagram.com/maanviofficial/",
  maps: "https://maps.app.goo.gl/yzy3N5ef7hTZ5goFA",
};
const years = Array.from({ length: 10 }, (_, index) => 2017 + index);
const seasons = ["Spring", "Summer", "Fall"];
const initialQuiz: Quiz = { occasion: "", forWhom: "", explore: [], budget: "", colors: [], colorNotes: "", notes: "", name: "", email: "", phone: "", country: "" };
const occasionOptions = ["Wedding", "Engagement", "Reception", "Festival", "Temple / traditional occasion", "Work / formal event", "Gift", "Celebration", "Something for myself", "Other"];
const whomOptions = ["Myself", "Bride", "Mother of the bride/groom", "Family member", "Gift", "Other"];
const exploreOptions = ["Silk sarees", "Lightweight sarees", "Wedding sarees", "Traditional weaves", "Contemporary sarees", "Dress materials", "Half sarees", "Not sure — curate for me"];
const budgets = ["Under ₹10,000 · under $120", "₹10,000–₹20,000 · $120–$240", "₹20,000–₹35,000 · $240–$420", "₹35,000–₹60,000 · $420–$720", "₹60,000+ · $720+", "Flexible / show me your recommendations"];
const colorChoices = [["Vermilion", "#aa3b24"], ["Marigold", "#d78b2d"], ["Lotus", "#c88b8d"], ["Aubergine", "#563143"], ["Peacock", "#1f5e5b"], ["Indigo", "#31486d"], ["Ivory", "#eee5d3"], ["Black", "#24211e"]];

function getRoute(): Route { const path = window.location.pathname !== "/" ? window.location.pathname.replace(/\/$/, "") : "/"; return (Object.entries(routes) as [Route, string][]).find(([, value]) => value === path)?.[0] ?? "home"; }
function track(name: string, detail: Record<string, unknown> = {}) { window.dispatchEvent(new CustomEvent("maanvi:analytics", { detail: { name, ...detail } })); (window as Window & { gtag?: (...args: unknown[]) => void }).gtag?.("event", name, detail); }
function BrandMark() { return <span className="brand-mark"><img src="/logo/maanvi-logo.png" alt="Maanvi" /><span className="brand-tagline" lang="te">మన మాన్వి మన వేడుక</span></span>; }
function AppLink({ to, children, className = "", onClick, ...rest }: { to: Route; children: React.ReactNode; className?: string; onClick?: () => void; [key: string]: unknown }) { return <a href={routes[to]} className={className} {...rest} onClick={(event) => { event.preventDefault(); history.pushState({}, "", routes[to]); window.dispatchEvent(new PopStateEvent("popstate")); onClick?.(); scrollTo({ top: 0, behavior: "smooth" }); }}>{children}</a>; }

function Header({ route }: { route: Route }) {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><AppLink to="home" className="brand-link"><BrandMark /></AppLink><button className="menu-button" type="button" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}><span /><span /></button><nav className={open ? "nav-open" : ""} aria-label="Main navigation">{navItems.map(([key, label]) => <AppLink key={key} to={key} className={route === key ? "active" : ""} onClick={() => setOpen(false)}>{label}</AppLink>)}<AppLink to="book" className="nav-cta" onClick={() => { setOpen(false); track("header_book_clicked"); }}>Book a Private Viewing</AppLink></nav></header>;
}
function Footer() { return <footer className="footer"><div><BrandMark /><p>Celebrating Maanvi, celebrating you.</p><p className="location-line">Vijayawada · Est. 2017</p></div><div className="footer-links"><AppLink to="archive">The Archive</AppLink><AppLink to="private-shopping">Private Shopping</AppLink><AppLink to="story">Our Story</AppLink><AppLink to="visit">Visit Maanvi</AppLink></div><div><p className="eyebrow">CONNECT</p><a href={externalLinks.instagram} target="_blank" rel="noreferrer">Instagram</a><br /><a href={externalLinks.whatsapp} target="_blank" rel="noreferrer">WhatsApp</a><br /><AppLink to="book" className="text-link">Book a private viewing →</AppLink></div><div className="footer-base"><span>© {new Date().getFullYear()} Maanvi</span><span lang="te">మన మాన్వి మన వేడుక</span><span>Vijayawada, Andhra Pradesh</span></div></footer>; }
function PageIntro({ eyebrow, title, body }: { eyebrow: string; title: React.ReactNode; body: string }) { return <section className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{body}</p></section>; }
function DrapeDivider({ pale = false }: { pale?: boolean }) { return <div className={`drape-divider ${pale ? "drape-divider-pale" : ""}`} aria-hidden="true"><span /><span /><span /></div>; }

function Home() { return <><section className="hero"><img src="/images/hero/maanvi-salt-flats-original.jpg" alt="A Maanvi woman wearing a lime saree in a mountain landscape" fetchPriority="high" /><div className="hero-shade" /><div className="hero-copy"><p className="eyebrow light">VIJAYAWADA · EST. 2017</p><h1 lang="te">మన మాన్వి<br /><em>మన వేడుక</em></h1><p className="hero-signature">Celebrating Maanvi, celebrating you.</p><p>A family-owned saree house rooted in warmth, trust and timeless style—now bringing Maanvi’s personal curation to clients everywhere.</p><div className="hero-actions"><AppLink to="book" className="button light-button" onClick={() => track("homepage_cta_clicked")}>Book a Private Viewing</AppLink><AppLink to="archive" className="text-link light-link" onClick={() => track("archive_opened", { source: "home" })}>Explore the Archive →</AppLink></div></div></section><DrapeDivider />
  <section className="experience section-pad"><div className="section-heading"><p className="eyebrow">THE MAANVI EXPERIENCE</p><h2>Shopping, made <em>personal.</em></h2><p>You bring us the occasion. We bring out the pieces worth seeing.</p></div><div className="steps">{[["01", "Discover", "Explore the Maanvi Archive and save the colors, drapes and moods that speak to you."], ["02", "Tell us", "Share your occasion, preferences, colors and budget in a few thoughtful questions."], ["03", "We curate", "Before you meet, Maanvi prepares a personalized selection from current arrivals."], ["04", "Meet Maanvi", "Join a focused 30-minute private video consultation from anywhere in the world."], ["05", "Choose", "See each piece live and purchase only what you genuinely love."]].map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="archive-teaser"><div className="arch-shape shape-one" /><div className="arch-shape shape-two" /><div className="arch-shape shape-three" /><div className="archive-teaser-copy"><p className="eyebrow light">THE MAANVI ARCHIVE</p><h2>A house of color,<br /><em>remembered.</em></h2><p>Our visual history is being carefully assembled from verified photographs. Save what you love; availability is never implied.</p><AppLink to="archive" className="button light-button">Enter the Archive</AppLink></div></section><DrapeDivider pale />
  <section className="manifesto section-pad"><p className="eyebrow">A FAMILY HOUSE OF SAREES</p><blockquote>“Celebrating Maanvi,<br />celebrating you.”</blockquote><p>From weddings and festivals to first drapes and family milestones, Maanvi has helped make celebration personal since 2017. We bring sarees, textiles, dress materials, half-sarees and traditional clothing from across India into one welcoming place.</p><AppLink to="story" className="text-link">Meet the Maanvi family →</AppLink></section><Callout /></>; }

function Callout() { return <section className="callout"><p className="eyebrow light">YOUR PRIVATE SAREE VIEWING</p><h2>Let us bring the right pieces <em>to you.</em></h2><p>30-minute video consultation · personally curated around your occasion</p><AppLink to="book" className="button light-button">Book a Private Viewing</AppLink></section>; }

function Archive({ favorites, toggleFavorite }: { favorites: string[]; toggleFavorite: (id: string) => void }) {
  const [year, setYear] = useState(2026); const [season, setSeason] = useState("Fall");
  useEffect(() => track("archive_year_viewed", { year }), [year]);
  const id = `${year}-${season.toLowerCase()}`; const locked = year === 2026 && season === "Fall";
  return <><PageIntro eyebrow="THE MAANVI ARCHIVE" title={<>A visual history of <em>what moved us.</em></>} body="A glimpse into the colors, weaves and pieces that have passed through Maanvi over the years. Archive pieces may no longer be available, but they help us understand what you love." /><section className="archive-browser"><div className="year-strip" role="tablist" aria-label="Archive years">{years.map((item) => <button role="tab" aria-selected={year === item} key={item} onClick={() => { setYear(item); setSeason(item === 2026 ? "Fall" : "Spring"); }}>{item}</button>)}</div><div className="season-strip">{seasons.map((item) => <button className={season === item ? "selected" : ""} key={item} onClick={() => setSeason(item)}>{item}</button>)}</div>
  {locked ? <div className="locked-collection"><div className="lock-ornament"><span>2026</span></div><div><p className="eyebrow light">PRIVATE COLLECTION</p><h2>Fall 2026</h2><p>The newest Maanvi collection is available through private viewing.</p><p>Tell us what you’re looking for and we’ll prepare a selection from our newest arrivals before your appointment.</p><AppLink to="book" className="button light-button">Reserve a Private Viewing</AppLink></div></div> : <div className="archive-empty"><div className="archive-folio"><span>{year}</span><i>{season}</i></div><div><p className="eyebrow">FROM THE MAANVI ARCHIVE</p><h2>{year} · {season}</h2><p>This chapter is awaiting verified, publication-approved Maanvi photographs. It remains intentionally quiet rather than filling history with unverified imagery.</p><button className={`save-button ${favorites.includes(id) ? "saved" : ""}`} onClick={() => toggleFavorite(id)}>{favorites.includes(id) ? "♥ Saved as inspiration" : "♡ I love this chapter"}</button></div></div>}<p className="archive-disclaimer">Archive imagery is inspiration, not live inventory. Availability is confirmed only during a private viewing.</p></section><Callout /></>;
}

function PrivateShopping() { const paymentUrl = import.meta.env.VITE_PAYMENT_URL as string | undefined; const paymentLabel = (import.meta.env.VITE_PAYMENT_LABEL as string | undefined) || "Continue to secure checkout"; return <><PageIntro eyebrow="MAANVI PRIVATE VIEWING" title={<>Your saree search,<br /><em>beautifully narrowed.</em></>} body="Thirty thoughtful minutes, prepared around you. Tell us what matters before we meet, and the Maanvi family will curate the current pieces most worth your time." /><section className="private-grid section-pad"><div className="number-card"><span>30</span><p>minutes, thoughtfully prepared</p></div><div><p className="eyebrow">HOW IT WORKS</p><h2>Personal from the very beginning.</h2><ol><li><b>Share your brief.</b><span>Occasion, colors, budget and anything you already love.</span></li><li><b>We prepare.</b><span>Maanvi selects suitable pieces from the newest available arrivals.</span></li><li><b>See every detail live.</b><span>Meet by private video from your own time zone.</span></li><li><b>Choose without pressure.</b><span>Purchase only the pieces that feel right.</span></li></ol></div></section><section className="payment-path"><div><p className="eyebrow light">ONE CLEAR CHECKOUT</p><h2>Chosen with care.<br /><em>Paid for securely.</em></h2></div><div><p>After your viewing, Maanvi confirms the saree, delivery details and complete total before sharing one secure payment link. International clients see the same simple handoff, with no surprise charge at the consultation stage.</p>{paymentUrl ? <a className="button light-button" href={paymentUrl} target="_blank" rel="noreferrer">{paymentLabel}</a> : <p className="checkout-ready">Secure checkout connection prepared · payment account pending</p>}</div></section><section className="credit-note"><p className="eyebrow">BOOK YOUR CONSULTATION</p><h2>30 minutes</h2><p>Choose a time that works for you. Your answers help the Maanvi family prepare a relevant selection before the call, so the conversation can stay focused on what you love.</p><AppLink to="book" className="button dark-button">Begin your private viewing</AppLink></section></>; }

function Bridal() { return <><PageIntro eyebrow="MAANVI BRIDAL" title={<>For a day held<br /><em>in memory.</em></>} body="Bridal shopping deserves attention, context and time. Share the ceremony, traditions, palette and people you are dressing; we will prepare a private selection for you." /><section className="editorial-split section-pad"><div className="fabric-panel bridal-fabric"><img src="/images/collections/bridal.jpg" alt="A Maanvi bridal saree selection arranged with traditional jewellery" /></div><div><p className="eyebrow">CURATED AROUND YOUR WEDDING</p><h2>Not a catalogue. A conversation.</h2><p>Whether you are shopping for the bride, mothers, family or the events around the wedding, your private viewing begins with understanding the role each saree will play.</p><ul><li>Ceremony and setting</li><li>Family traditions and preferences</li><li>Colors, drape and comfort</li><li>Budget and time frame</li></ul><AppLink to="book" className="button dark-button">Plan a Bridal Viewing</AppLink></div></section><Callout /></>; }
function Guide() { const guides = [["01", "Silk sarees", "A broad family of sarees whose feel, weight and formality vary by silk, weave and finishing."], ["02", "Lightweight sarees", "Chosen for ease of drape and movement; the fabric and construction determine their character."], ["03", "Traditional weaves", "Regional weaving traditions carry distinct structures and visual languages. Origin should always be verified piece by piece."], ["04", "Care & keeping", "Storage and cleaning depend on fiber, weave, dye and embellishment. Ask for guidance for the specific saree you choose."]]; return <><PageIntro eyebrow="ACROSS INDIA" title={<>A thoughtful guide to<br /><em>finding your saree.</em></>} body="An editorial introduction for younger and international clients. We keep guidance useful and factual—and confirm the origin, feel and care of every piece during your private viewing." /><section className="guide-grid section-pad">{guides.map(([n, title, copy]) => <article key={n}><span>{n}</span><h2>{title}</h2><p>{copy}</p><p className="coming">Detailed guide coming as Maanvi’s represented weaves are verified.</p></article>)}</section><Callout /></>; }
function Story() { return <><PageIntro eyebrow="మా కథ · OUR STORY" title={<>A family house<br /><em>woven with celebration.</em></>} body="Maanvi began in Vijayawada with a simple intention: to be part of people’s happiest moments through sarees chosen with care, taste and trust." /><section className="story-origin section-pad"><div className="story-family-photo"><img src="/images/story/founders.jpg" alt="The family behind Maanvi" /></div><div className="founders-note"><p className="eyebrow">FOUNDER’S NOTE</p><p lang="te">భారతదేశం నలుమూలల నుంచి వచ్చిన చీరల సౌందర్యం, రంగులు, కథలు... అన్నీ ఒకేచోట చేరే చిన్న గృహం పేరు మాన్వి. ప్రతి పండుగకు, ప్రతి కొత్త ఆరంభానికి, ఒక ప్రత్యేకమైన చీరను ఎంచుకునే ఆ ఆనందాన్ని మీకు అందించాలనే ఆలోచనతో ఈ ప్రయాణం మొదలైంది.</p><p lang="te">ఈ రోజు మాన్వి మొదలై తొమ్మిది సంవత్సరాలు గడిచింది. ఈ ప్రయాణంలో మేము కేవలం చీరలను మాత్రమే కాదు, వాటి వెనుక ఉన్న జ్ఞాపకాలను, సంస్కృతిని మరియు వేడుకల ఆనందాన్ని కూడా పంచుకుంటున్నాం. ఇలాగే మీ ప్రతి వేడుకలో మాన్వి భాగం కావాలని మేము కోరుకుంటున్నాం. మగువలకు, మగ్గములకు మధ్య వారధిగా మాన్వి నిలబడాలని ఆశిస్తున్నాం.</p><p className="founders-signoff" lang="te">మీ మాన్వి కుటుంబం నుండి ♥</p></div></section><section className="story-body section-pad"><div><p className="dropcap">Over the years, Maanvi has grown into more than a saree house. It is a place where weddings, festivals, first drapes and family memories are wrapped in color and tradition.</p><p>Our role is to listen well, bring together a thoughtful selection, and help each person find what feels right for her celebration.</p></div><div className="story-quote"><img src="/logo/maanvi-logo.png" alt="" /><blockquote>Since 2017.<br />From our family<br />to yours.</blockquote></div></section><section className="location-banner"><p className="eyebrow light">OUR HOME</p><h2>Vijayawada · India</h2><AppLink to="visit" className="text-link light-link">Plan your visit →</AppLink></section></>; }
function Visit() { return <><PageIntro eyebrow="VISIT MAANVI" title={<>Come see us<br /><em>in Vijayawada.</em></>} body="Visit our family-run saree house in NTR Colony, or book a private video consultation from wherever you are." /><section className="visit-grid section-pad"><div className="store-card"><img src="/images/visit/store.jpg" alt="Maanvi ninth-anniversary invitation in Telugu" /></div><div><p className="eyebrow">PLAN YOUR VISIT</p><h2>A warmer, more personal way to shop.</h2><p>No. 52-1-7/5, Road Number 2A, near Malineni Library Hall, NTR Colony, Veterinary Colony, Kanuru, Andhra Pradesh 520008, India.</p><dl><dt>Call or WhatsApp</dt><dd><a href={externalLinks.whatsapp} target="_blank" rel="noreferrer">+91 91822 42429</a></dd><dt>Directions</dt><dd><a href={externalLinks.maps} target="_blank" rel="noreferrer">Open Google Maps ↗</a></dd><dt>Instagram</dt><dd><a href={externalLinks.instagram} target="_blank" rel="noreferrer">@maanviofficial ↗</a></dd></dl><AppLink to="book" className="button dark-button">Book a Private Viewing</AppLink></div></section></>; }

function Choice({ selected, children, onClick }: { selected: boolean; children: React.ReactNode; onClick: () => void }) { return <button type="button" className={`choice ${selected ? "selected" : ""}`} aria-pressed={selected} onClick={onClick}>{children}<span>{selected ? "✓" : ""}</span></button>; }
function Booking({ favorites }: { favorites: string[] }) {
  const [step, setStep] = useState(() => Number(sessionStorage.getItem("maanvi.quiz.step") || 0));
  const [quiz, setQuiz] = useState<Quiz>(() => { try { return { ...initialQuiz, ...JSON.parse(localStorage.getItem("maanvi.quiz") || "{}") }; } catch { return initialQuiz; } });
  const calendlyUrl = (import.meta.env.VITE_CALENDLY_URL as string | undefined) || externalLinks.calendly; const whatsappUrl = (import.meta.env.VITE_WHATSAPP_URL as string | undefined) || externalLinks.whatsapp;
  useEffect(() => { localStorage.setItem("maanvi.quiz", JSON.stringify(quiz)); sessionStorage.setItem("maanvi.quiz.step", String(step)); }, [quiz, step]);
  useEffect(() => { if (step === 0) track("quiz_started"); }, [step]);
  const canContinue = [Boolean(quiz.occasion), Boolean(quiz.forWhom), quiz.explore.length > 0, Boolean(quiz.budget), true, Boolean(quiz.name && quiz.email), true][step];
  const next = () => { if (step < 6) { const nextStep = step + 1; setStep(nextStep); if (nextStep === 6) track("quiz_completed", { favorites: favorites.length }); } };
  const update = <K extends keyof Quiz>(key: K, value: Quiz[K]) => setQuiz({ ...quiz, [key]: value });
  const toggleArray = (key: "explore" | "colors", value: string) => update(key, quiz[key].includes(value) ? quiz[key].filter((item) => item !== value) : [...quiz[key], value]);
  const calendlyTarget = useMemo(() => { if (!calendlyUrl) return ""; const url = new URL(calendlyUrl); url.searchParams.set("name", quiz.name); url.searchParams.set("email", quiz.email); url.searchParams.set("a1", `${quiz.occasion}; ${quiz.forWhom}`); url.searchParams.set("a2", quiz.budget); url.searchParams.set("a3", [...quiz.explore, ...quiz.colors].join(", ")); return url.toString(); }, [calendlyUrl, quiz]);
  return <section className="booking-page"><div className="booking-aside"><BrandMark /><p className="eyebrow light">MAANVI PRIVATE VIEWING</p><h1>Tell us what<br /><em>you’re looking for.</em></h1><p>A few thoughtful details help our family prepare pieces that feel like you.</p><div className="booking-facts"><span>30-minute video consultation</span><span>Curated around your occasion</span><span>From Vijayawada, with care</span></div></div><div className="booking-form"><AppLink to="home" className="close-booking" aria-label="Close booking">×</AppLink><div className="progress" aria-label={`Step ${Math.min(step + 1, 7)} of 7`}><span style={{ width: `${((step + 1) / 7) * 100}%` }} /></div>
  {step === 0 && <QuizStep n="01" title="What are you shopping for?" hint="Choose the occasion that feels closest."><div className="choice-grid">{occasionOptions.map((item) => <Choice key={item} selected={quiz.occasion === item} onClick={() => update("occasion", item)}>{item}</Choice>)}</div></QuizStep>}
  {step === 1 && <QuizStep n="02" title="Who are you shopping for?" hint="This helps us think about the person and the moment."><div className="choice-grid">{whomOptions.map((item) => <Choice key={item} selected={quiz.forWhom === item} onClick={() => update("forWhom", item)}>{item}</Choice>)}</div></QuizStep>}
  {step === 2 && <QuizStep n="03" title="What would you like to explore?" hint="Choose as many as you like."><div className="choice-grid">{exploreOptions.map((item) => <Choice key={item} selected={quiz.explore.includes(item)} onClick={() => toggleArray("explore", item)}>{item}</Choice>)}</div></QuizStep>}
  {step === 3 && <QuizStep n="04" title="What feels comfortable?" hint="Approximate USD equivalents help international clients and may vary."><div className="choice-stack">{budgets.map((item) => <Choice key={item} selected={quiz.budget === item} onClick={() => update("budget", item)}>{item}</Choice>)}</div></QuizStep>}
  {step === 4 && <QuizStep n="05" title="Which colors are calling you?" hint="Choose a few, or tell us something more specific."><div className="color-grid">{colorChoices.map(([name, color]) => <button type="button" key={name} aria-pressed={quiz.colors.includes(name)} className={quiz.colors.includes(name) ? "selected" : ""} onClick={() => toggleArray("colors", name)}><i style={{ background: color }} /><span>{name}</span></button>)}</div><label className="field"><span>Color notes (optional)</span><input value={quiz.colorNotes} onChange={(e) => update("colorNotes", e.target.value)} placeholder="For example: no pastels, or open to surprises" /></label></QuizStep>}
  {step === 5 && <QuizStep n="06" title="How may we reach you?" hint="Your details are used only to prepare and manage your appointment."><div className="field-grid"><label className="field"><span>Name</span><input autoComplete="name" value={quiz.name} onChange={(e) => update("name", e.target.value)} /></label><label className="field"><span>Email</span><input type="email" autoComplete="email" value={quiz.email} onChange={(e) => update("email", e.target.value)} /></label><label className="field"><span>Phone / WhatsApp</span><input type="tel" autoComplete="tel" value={quiz.phone} onChange={(e) => update("phone", e.target.value)} placeholder="Include country code" /></label><label className="field"><span>Country / time zone</span><input autoComplete="country-name" value={quiz.country} onChange={(e) => update("country", e.target.value)} placeholder="e.g. California, USA" /></label></div><label className="field"><span>Anything you want us to know?</span><textarea value={quiz.notes} onChange={(e) => update("notes", e.target.value)} rows={4} /></label></QuizStep>}
  {step === 6 && <QuizStep n="READY" title="We know what to bring out for you." hint="Review the essentials, then choose your 30-minute consultation in your own time zone."><div className="summary"><p><span>Occasion</span>{quiz.occasion}</p><p><span>Shopping for</span>{quiz.forWhom}</p><p><span>Explore</span>{quiz.explore.join(", ")}</p><p><span>Budget</span>{quiz.budget}</p><p><span>Colors</span>{quiz.colors.join(", ") || "Curate for me"}</p><p><span>Archive inspiration</span>{favorites.length ? `${favorites.length} saved chapter${favorites.length > 1 ? "s" : ""}` : "None saved yet"}</p></div><div className="policy"><strong>Your consultation</strong><p>Maanvi uses your answers to prepare a thoughtful selection before the call. Scheduling is completed securely through the official Calendly page.</p></div><a className="button dark-button full" href={calendlyTarget} onClick={() => track("calendly_opened")} target="_blank" rel="noreferrer">Choose an appointment time</a>{whatsappUrl && <a href={whatsappUrl} target="_blank" rel="noreferrer" className="text-link centered" onClick={() => track("whatsapp_clicked")}>Message Maanvi →</a>}</QuizStep>}
  {step < 6 && <div className="form-actions">{step > 0 && <button type="button" className="back-button" onClick={() => setStep(step - 1)}>← Back</button>}<button type="button" className="button dark-button" disabled={!canContinue} onClick={next}>Continue →</button></div>}</div></section>;
}
function QuizStep({ n, title, hint, children }: { n: string; title: string; hint: string; children: React.ReactNode }) { return <div className="quiz-step"><p className="eyebrow">STEP {n}</p><h2>{title}</h2><p className="quiz-hint">{hint}</p>{children}</div>; }

export default function App() {
  const [route, setRoute] = useState<Route>(getRoute); const [favorites, setFavorites] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("maanvi.favorites") || "[]"); } catch { return []; } });
  useEffect(() => { const onRoute = () => setRoute(getRoute()); addEventListener("popstate", onRoute); return () => removeEventListener("popstate", onRoute); }, []);
  useEffect(() => { document.title = route === "home" ? "Maanvi — మన మాన్వి మన వేడుక" : `${navItems.find(([key]) => key === route)?.[1] || "Book a Private Viewing"} | Maanvi`; document.querySelector('meta[name="description"]')?.setAttribute("content", route === "book" ? "Book a 30-minute private Maanvi saree consultation, curated around your occasion, style and budget." : "Maanvi is a family-owned saree house in Vijayawada, celebrating tradition, personal service and meaningful occasions since 2017."); }, [route]);
  const toggleFavorite = (id: string) => { const next = favorites.includes(id) ? favorites.filter((item) => item !== id) : [...favorites, id]; setFavorites(next); localStorage.setItem("maanvi.favorites", JSON.stringify(next)); track("archive_image_favorited", { id, saved: next.includes(id) }); };
  if (route === "book") return <Booking favorites={favorites} />;
  const pages: Record<Exclude<Route, "book">, React.ReactNode> = { home: <Home />, archive: <Archive favorites={favorites} toggleFavorite={toggleFavorite} />, "private-shopping": <PrivateShopping />, bridal: <Bridal />, guide: <Guide />, story: <Story />, visit: <Visit /> };
  return <div className="app"><Header route={route} /><main>{pages[route]}</main><Footer /></div>;
}
